# Site settings
title: Yashwanth MG
tagline: Business Development Specialist. # it will display as the sub-title
description: Welcome to my professional portfolio website, where you can delve into my career trajectory, achievements, skill set, and creative projects.
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://yashwanthmg.github.io/" # the base hostname & protocol for your site, e.g., http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Permalinks
permalink: pretty # Options: pretty, date, ordinal

# Layouts
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

# Pagination
paginate: 5

# Exclude files and directories
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default-layout"
  -
    scope:
      path: "_posts"
    values:
      layout: "post-layout"

# Collections
collections:
  my_collection:
    output: true

# Output settings
output:
  relative_url: false

# Date format
date_format: "%b %-d, %Y"

# Feed settings
feed:
  path: atom.xml
  limit: 10

# SEO and Social
author: Get in touch
email: yashwanthmg93@gmail.com
linkedin_username: yashwanth-mg
github_username: yashwanthmg

# Navigation
navigation:
  - title: Home
    url: "/"
  - title: About
    url: "/about/"
  - title: Blog
    url: "/blog/"
